Repository team-BEBEBE/Monty-Hall-problem-team, pull requests merged in 2023-05, with the labels that each got.

#4 몬티홀(1회) 결과값 반환
  monty_hall_random.py
Labels: Priority : Medium

#5 feat: return monty-hall input
  monty_hall_input.py
Labels: Priority : Medium, Type : Enhancement

#6 Monty Hall Problem's Main 완성
  montyHall.py
Labels: Priority : Medium, Type : Enhancement

#10 fix: change import module name
  __pycache__/monty_hall_random.cpython-310.pyc
  montyHall.py
Labels: Priority : Urgent, Domain : Python, Type : Bug
